[package]
name = "cryptominisat"
version = "0.1.0"
authors = ["Robert Grosse <n210241048576@gmail.com>"]
links = "cryptominisat5"
build = "build.rs"
license = "LGPL-2.1/MIT"

[dependencies]
libc = "0.2.0"

[build-dependencies]
cmake = "0.1.17"
